### PR TITLE
Remove LD_LIBRARY_PATH instructions

### PR DESCRIPTION
**Pull request by jacobvosmaer**
This simplifies the instructions for developers and our CI settings.

### CODE REVIEW

**Comment by robinst** [comment]
Is it not necessary anymore?

**Comment by jacobvosmaer** [comment]
@robinst wouldn't CI fail if it was still needed? I also don't need it locally.

**Comment by jacobvosmaer** [comment]
When you run `TAGLIB_DIR=/foo/taglib rake compile`, the path `/foo/taglib` is stored in your Ruby C extension. The moment you load the C extension it will use `/foo/taglib`. Only if you want to use a different taglib location from the one the C extension was compiled with would you need LD_LIBRARY_PATH.

This is why `bundle exec rake test` works correctly in CI without any information about where taglib is installed: that information is contained in the Ruby C extension files already.

**Comment by jacobvosmaer** [comment]
I wonder if the need to use LD_LIBRARY_PATH had to do with the problem solved (in `taglib-2`, not `main`) by https://github.com/robinst/taglib-ruby/pull/131.

Namely, if you have a TagLib installation in `/usr/local`, then `rake compile` _ignores_ `TAGLIB_DIR` even when it is set. So then you would get a Ruby C extension that wants to load TagLib from `/usr/local`. In that case LD_LIBRARY_PATH could force Ruby to use your TagLib in tmp/ instead. But the solution for that problem is to make `rake compile` respect TAGLIB_DIR in the first place, not to first compile the wrong path into the C extension and then override it at runtime.

**Comment by robinst** [comment]
Was just wondering why we even had it in the first place. Merged!

**Pull request merged**
