### PR TITLE
Wrap taglib-1.11 Ogg/Picture methods for backward compatibility

### LINKED ISSUE #78: Support for Taglib 1.11.1
Hi everyone,

Taglib 1.11.1 starts being quite mainstream: Debian stable, Ubuntu 17.10, Fedora 25/26/27, the next Mint...

Unfortunately, Taglib 1.11 introduced a new way to handle pictures in Ogg files. They were previously accessed as standard tags (base64-encoded), but are now available as a list of FLAC::Picture objects. Which means that on those modern distributions, Taglib-ruby (which is based on Taglib 1.7 if I'm correct) can't access pictures from Ogg files anymore.

Since a tool of mine requires this feature, I'm willing to try to upgrade Taglib-ruby for a Taglib 1.11.1 support. I've never used Swig or native gems before, just played a bit on the last few weeks, but it seems doable and fun.

Any thought/advice/suggestion?

### PR DESCRIPTION
**Pull request by Sigill**
Starting with taglib-1.11, pictures of a XiphComment are not accessible as
standard text fields but through a dedicated list. For backward compatibility,
the following methods are extended to handle pictures as standard text fields again.

The XiphComment::field_list_map method will report a METADATA_BLOCK_PICTURE field
containing the pictures, in the METADATA_BLOCK_PICTURE format, base64-encoded.

The XiphComment::add_field method will add/replace pictures to the dedicated list.
The value is expected to have the format associated to the key (METADATA_BLOCK_PICTURE
or COVERART). If the format is COVERART, the picture is converted to the
METADATA_BLOCK_PICTURE format.

The XiphComment::remove_field method will clear or remove pictures from the dedicated
list. Since the field_list_map does not expose COVERART pictures, this method only
support pictures in the METADATA_BLOCK_PICTURE format.

Wrappers are generated on taglib-1.7.2 using swig 3.0.7.

Closes #78

### CODE REVIEW

**Comment by robinst** [comment]
Hey! While this pull request looks like a great way to still support TagLib < 1.11, I'd rather raise the minimum required version for taglib-ruby to TagLib 1.11 (being in Debian stable is good enough for me).

That way, we can get rid of all the complexity of maintaining backwards compatibility and just add the methods for working with pictures without any `#if` sections.

Would you mind raising another pull request that does that?

**Comment by Sigill** [comment]
I've actually mostly done it (that was the PR I was going to submit last
week, but I changed my mind at the last minute).
And I was going to ask for your opinion about abandonning support for older
versions, so yes, I'll submit another PR.
I still think this one should be integrated, is that OK for you?


2018-02-19 2:11 GMT+01:00 Robin Stocker <notifications@github.com>:

**Comment by robinst** [comment]
> I still think this one should be integrated, is that OK for you?

Not sure, I want to keep the wrapper as thin as possible without any potentially surprising behavior on top of what TagLib itself does. So I'd prefer to just wrap the new methods without adding any "compatibility" code.

**Comment by robinst** [comment]
It just seems like having this compatibility code that does more things than what the methods normally do would mean that you *can't* do some things that you could otherwise do, for example:

* I want to write a file with the deprecated COVERART field (let's say I'm trying to write a file that an application can read that only supports COVERART). With the code from this PR, I can't do that because it will get rewritten to a picture.
* I want to remove a specific field, so I do `remove_field("METADATA_BLOCK_PICTURE")`. But because of the compat code, it removes all pictures instead..

**Comment by Sigill** [comment]
Taglib-1.11 has dropped support for COVERART field, which is considered as deprecated. The C++ API still allow to insert a `COVERART` field (by inserting a standard text field instead of a picture object), but that's a bit tricky since it will get automatically converted to `METADATA...` the second time Taglib is used to edit the file. I wouldn't recommend playing with `COVERART` fields with Taglib-1.11.

When you say that doing `remove_field("METADATA_BLOCK_PICTURE")` will remove all pictures, were you trying to remove a single picture or remove the whole `METADATA...` field (vs the `COVERART` one)? In the first case, removal of a single picture is still possible, nothing has changed. In the second case, that's not my compatibility code, but due to Taglib-1.11 having dropped support for the `COVERART` field.

**Comment by robinst** [comment]
Hmm. I appreciate trying to fix this, but I'm fairly certain that not adding any additional logic on top of TagLib is the right call. I'm going to decline this, sorry.

Please raise a pull request for just supporting TagLib 1.11. When we release it, we can bump the major version to 1.0.0 to make it clear that there was a break in behavior.

**Pull request closed without merging**
